AllCops:
  TargetRubyVersion: 2.5.1
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'

Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - '/**/*.gemspec'

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*.rb'
